package com.redcheck.backend.dto.response;

import lombok.Builder;

import java.time.LocalDateTime;

@Builder
public record CalendarEventResponseDTO(
        Long id,
        String title,
        String description,
        LocalDateTime startDateTime,
        LocalDateTime endDateTime,
        boolean allDay,
        Long categoryId,
        // Non-null when this occurrence was generated by a
        // RecurringCalendarEvent routine — same "just the id, frontend
        // joins locally against state it already holds" convention as
        // TaskResponseDTO.subjectId / RecurringTaskResponseDTO.subjectId.
        Long recurringEventId
) {}
