spring:
  application:
    name: RedCheck

  datasource:
    url: jdbc:mysql://localhost:3306/redcheck_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: redcheck_user
    password: redcheck_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/schema-generado.sql

ai:
  provider: gemini

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash